# Copyright (c) 2011-2015 Wind River Systems, Inc.

# The right to copy, distribute, modify or otherwise make use
# of this software may be licensed only pursuant to the terms
# of an applicable Wind River license agreement.

# Makefile - generates a Nanokernel application

KERNEL_TYPE := nano
include Makefile.nanokernel

include ${ZEPHYR_BASE}/Makefile.inc
