# Copyright (c) 2011-2015 Wind River Systems, Inc.

# The right to copy, distribute, modify or otherwise make use
# of this software may be licensed only pursuant to the terms
# of an applicable Wind River license agreement.

# Makefile - generates a Microkernel application

MDEF_FILE := #PRJNAME#.mdef
KERNEL_TYPE = micro
include Makefile.microkernel

include ${ZEPHYR_BASE}/Makefile.inc
